#ifndef CONFIG_H
#define CONFIG_H

#define MAX_TIMERS 16
#define RINGING_TIMEOUT 10000

//UART configs
#define RX_BUFFER_SIZE 64


//Active_Timer_View configs
#define TIMERS_INDICATOR_COLUMN 0
#define RINGING_INDICATOR_COLUMN 1
#define DIGITS_X_OFFSET 3
#define DIGITS_Y_OFFSET 0
#define ACTIVE_TIMER_INDICATOR_BLINK_RATE 100
#define TIMER_DIGITS_BLINK_RATE 500

#endif // CONFIG_H
