name: Programmer

on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r programmer/requirements.txt
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest programmer
