name: Simulator

on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - name: Build
        run: |
          cd simulation && make

